# Generated by Django 4.2.4 on 2023-08-21 02:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0006_alter_profile_table'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='conversions',
            table='conversions',
        ),
        migrations.AlterModelTable(
            name='message',
            table='messages',
        ),
    ]
