# Generated by Django 4.2.4 on 2023-08-24 03:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0008_rename_content_message_message_conversions_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='conversions',
            name='name',
        ),
        migrations.RemoveField(
            model_name='conversions',
            name='type',
        ),
    ]
